<?php

namespace Tests\Feature;

use App\Models\Store;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserStoreTest extends TestCase
{

    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testThatUserHasStore()
    {
        $loggedUser = $this->loginUser();

        $store = factory(Store::class)->make();

        $loggedUser->stores()->create($store->toArray());

        $num_stores = $loggedUser->stores()->count();

        $this->assertGreaterThan(0, $num_stores);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testThatUserDoesntHaveAnyStore()
    {
        $loggedUser = $this->loginUser();

        $num_stores = $loggedUser->stores()->count();

        $this->assertEquals(0, $num_stores);
    }
}
